# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
type: Opaque
data:
  admin-user: Z3JhZmFuYWFkbWlu
  admin-password: Z3JhZmFuYWFkbWlu


# kubectl create secret generic grafana-admin-credentials \
#   --from-literal=admin-user='your-username' \
#   --from-literal=admin-password='your-secure-password'
